services:
  app:
    container_name: app_reon_berezovsky
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - MONGO_SERVER=mongodb://db/reon_berezovsky

  db:
    image: mongo
    container_name: mongo_reon_berezovsky
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
